name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build_releases:
    name: Build & Upload Release Asset
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm64
          - goos: darwin
            goarch: amd64
          - goos: darwin
            goarch: arm64
          - goos: windows
            goarch: amd64

    steps:
      - name: Check out runtime repo
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          check-latest: true

      - name: Download Go modules
        run: go mod download

      - name: Build Binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 0
        run: |
          OUTPUT_NAME=niceboy-${{ matrix.goos }}-${{ matrix.goarch }}
          if [ "${{ matrix.goos }}" = "windows" ]; then
            OUTPUT_NAME="${OUTPUT_NAME}.exe"
          fi
          go build -ldflags="-s -w" -o $OUTPUT_NAME cmd/niceboy/main.go

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: niceboy-${{ matrix.goos }}-${{ matrix.goarch }}*
